-- ============================================================================
-- CraveMap / 好吃GO — Restaurant Seed Data
-- ============================================================================
-- Apply AFTER supabase/schema.sql. Safe to re-run.
-- Source of truth: data/mockRestaurants.ts (32 records).
-- Seeds restaurant CMS content only; check-ins and user-owned data are not seeded.
-- ============================================================================

insert into public.restaurants (
  id,
  slug,
  name,
  city,
  neighborhood,
  cuisine,
  price,
  description,
  recommendation_reason,
  address,
  hours,
  phone,
  website,
  images,
  latitude,
  longitude,
  tags,
  categories,
  best_for,
  avoid_if,
  is_open,
  wait_time,
  insider_tip,
  what_locals_order,
  best_time_to_go,
  trending_signal,
  verified_check_ins,
  local_approved_percent,
  recent_visits
) values
  ('00000000-0000-4000-8000-000000000001', 'new-york-city-flushing-xi-an-famous-foods', 'Xi''an Famous Foods', 'New York City', 'Flushing', 'Chinese - Shaanxi', '$', 'Hand-pulled noodles from Shaanxi province. The biangbiang noodles are wide, chewy, and dressed in chili oil that will clear your sinuses.', '94% of people with your taste say the spicy cumin lamb noodles are the real deal', '133-31 39th Ave, Flushing, NY 11354', '11am - 9pm daily', '+1 718-888-6628', null, array['https://loremflickr.com/400/300/food?lock=xianfoods1', 'https://loremflickr.com/400/300/food?lock=xianfoods2']::text[], 40.7580000, -73.8303000, array['Actually Worth It', 'Local Favorite', 'Spicy', 'Authentic']::text[], array['local-approved', 'actually-spicy', 'hidden-gems', 'student-favorites']::text[], array['Spice lovers', 'Noodle enthusiasts', 'Authentic Chinese food']::text[], array['Sensitive to heat', 'Prefer fusion', 'Need lots of seating']::text[], true, '10 min', 'Ask for the noodles "extra al dente" — they''ll pull a fresh batch instead of from the pre-cooked tray. Game changer.', array['Biangbiang noodles in chili oil', 'Stewed cumin lamb noodles', 'Tiger vegetables', 'Spicy & tingly beef']::text[], 'Weekday 2pm — empty, fresh noodle batch, no judgment', 'classic', 847, 91, 142),
  ('00000000-0000-4000-8000-000000000002', 'new-york-city-flushing-nan-xiang-xiao-long-bao', 'Nan Xiang Xiao Long Bao', 'New York City', 'Flushing', 'Chinese - Shanghainese', '$$', 'The gold standard for soup dumplings in Flushing. Thin skin, rich broth, perfectly portioned pork filling.', 'Best XLB in NYC per 89% of local food scouts in your area', '38-12 Prince St, Flushing, NY 11354', '10:30am - 10pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=nanxiang1', 'https://loremflickr.com/400/300/food?lock=nanxiang2']::text[], 40.7593000, -73.8314000, array['Soup Dumplings', 'Local Favorite', 'Worth the Wait']::text[], array['local-approved', 'culture-approved', 'group-dinner']::text[], array['Dumpling fans', 'Date night', 'Group dinner']::text[], array['Hate crowds', 'Need fast service', 'Not into pork']::text[], true, '25 min', 'Put your name down, then walk to the New World Mall food court next door. They''ll text you. Don''t stand in the lobby like a tourist.', array['Pork XLB (2 steamers)', 'Crab roe XLB (seasonal)', 'Pan-fried buns (sheng jian bao)', 'Wood ear with vinegar']::text[], 'Sunday 10:30am — first steamers of the day, shortest wait', 'classic', 1203, 89, 187),
  ('00000000-0000-4000-8000-000000000003', 'new-york-city-flushing-white-bear', 'White Bear', 'New York City', 'Flushing', 'Chinese - Dumplings', '$', 'A cash-only counter with no English menu and no sign. Order the #6 (pork and chive wontons in chili oil) and prepare to question every other wonton you have ever had.', 'No sign, no menu in English, no Instagram — just the best wontons in NYC', '135-02 Roosevelt Ave, Flushing, NY 11354', '8am - 9pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=whitebear1', 'https://loremflickr.com/400/300/food?lock=whitebear2']::text[], 40.7561000, -73.8296000, array['Hidden Gem', 'Locals Only', 'Cash Only', 'No Sign']::text[], array['hidden-gems', 'local-approved', 'student-favorites', 'culture-approved']::text[], array['Adventurous eaters', 'Authentic Chinese', 'Budget diners']::text[], array['Need English menu', 'Prefer cards', 'Want ambiance']::text[], true, null, 'Bring small bills. Auntie will not break a $20 cheerfully. Order by pointing at #6 and holding up fingers.', array['#6 pork & chive wontons in chili oil', 'Beef noodle soup', 'Pork & cabbage dumplings']::text[], 'Tuesday or Wednesday 3pm — no line, fresh batch of wontons', 'underrated', 621, 95, 78),
  ('00000000-0000-4000-8000-000000000004', 'new-york-city-koreatown-kang-ho-dong-baekjeong', 'Kang Ho Dong Baekjeong', 'New York City', 'Koreatown', 'Korean BBQ', '$$$', 'Named after Korean wrestling champion Kang Ho Dong. Premium cuts, tableside service, and the egg soufflé steamed in the grill center is mandatory.', 'Best premium KBBQ in Manhattan per Korean expat community members', '1 E 32nd St, New York, NY 10016', '11:30am - 11pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=kbbq1', 'https://loremflickr.com/400/300/food?lock=kbbq2']::text[], 40.7466000, -73.9855000, array['KBBQ', 'Group Vibes', 'Actually Worth It']::text[], array['group-dinner', 'local-approved', 'date-night']::text[], array['Group dinners', 'Celebrations', 'KBBQ enthusiasts']::text[], array['Vegetarians', 'Budget diners', 'Solo dining']::text[], true, '45 min', null, array[]::text[], null, null, 1540, 84, 0),
  ('00000000-0000-4000-8000-000000000005', 'new-york-city-chinatown-spicy-village', 'Spicy Village', 'New York City', 'Chinatown', 'Chinese - Henan', '$', 'Henan-style Chinese with wide, chewy noodles. The big tray chicken (大盘鸡) arrives on a massive platter with hand-pulled noodles swimming in spiced gravy.', 'The big tray chicken is a cult classic — 93% of locals say it is essential Chinatown', '68 Forsyth St, New York, NY 10002', '11am - 10pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=spicyvillage1', 'https://loremflickr.com/400/300/food?lock=spicyvillage2']::text[], 40.7167000, -73.9943000, array['Spicy', 'Actually Worth It', 'Hidden Gem', 'Big Tray Chicken']::text[], array['actually-spicy', 'hidden-gems', 'local-approved', 'student-favorites']::text[], array['Spice lovers', 'Adventurous eaters', 'Budget diners']::text[], array['Heat sensitive', 'Need fancy ambiance']::text[], true, null, 'Order the big tray chicken "small" — it still feeds 3 people and saves you $14. Most newcomers over-order.', array['Big tray chicken (small)', 'Hand-pulled noodles (added at end)', 'Cucumber salad', 'Lamb skewers']::text[], 'Tuesday 6:30pm — busy enough to feel alive, empty enough to get a table', 'underrated', 432, 93, 92),
  ('00000000-0000-4000-8000-000000000006', 'new-york-city-chinatown-pho-bang', 'Pho Bang', 'New York City', 'Chinatown', 'Vietnamese', '$', 'No-frills pho that has been feeding Chinatown for decades. The broth is simmered all day and arrives clear, rich, and deeply beefy.', 'A Chinatown institution for 30+ years — locals keep coming back for the clean, rich broth', '3 Pike St, New York, NY 10002', '9am - 10pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=phobang1', 'https://loremflickr.com/400/300/food?lock=phobang2']::text[], 40.7132000, -73.9988000, array['Classic Pho', 'Local Staple', 'No Frills']::text[], array['local-approved', 'student-favorites', 'late-night']::text[], array['Pho lovers', 'Budget diners', 'Rainy-day comfort']::text[], array['Prefer modern interiors', 'Vegetarians (limited options)']::text[], true, null, null, array[]::text[], null, null, 389, 88, 0),
  ('00000000-0000-4000-8000-000000000007', 'new-york-city-jackson-heights-adda-indian-canteen', 'Adda Indian Canteen', 'New York City', 'Jackson Heights', 'Indian', '$$', 'A buzzy Indian canteen where the lamb keema with bone marrow is a must-order. Casual, loud, and genuinely delicious.', 'Indian diaspora in Jackson Heights votes this #1 for authentic home-style cooking', '31-31 Thomson Ave, Long Island City, NY 11101', '5pm - 11pm Mon-Fri, 12pm - 11pm Sat-Sun', null, null, array['https://loremflickr.com/400/300/food?lock=adda1', 'https://loremflickr.com/400/300/food?lock=adda2']::text[], 40.7446000, -73.9360000, array['Authentic Indian', 'Local Canteen', 'Lamb', 'Chaat']::text[], array['local-approved', 'culture-approved', 'group-dinner']::text[], array['Indian food lovers', 'Group dinners', 'Adventurous eaters']::text[], array['Vegetarians (limited)', 'Need quiet setting']::text[], true, '20 min', null, array[]::text[], null, null, 567, 92, 0),
  ('00000000-0000-4000-8000-000000000008', 'new-york-city-astoria-taverna-kyclades', 'Taverna Kyclades', 'New York City', 'Astoria', 'Greek Seafood', '$$$', 'A beloved Greek seafood taverna in Astoria. The whole grilled fish is perfectly seasoned, and the spanakopita is buttery and crisp.', 'Astoria Greek community staple — the grilled octopus is the benchmark', '33-07 Ditmars Blvd, Astoria, NY 11105', '12pm - 11pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=kyclades1', 'https://loremflickr.com/400/300/food?lock=kyclades2']::text[], 40.7745000, -73.9116000, array['Seafood', 'Greek', 'Local Institution']::text[], array['local-approved', 'date-night', 'group-dinner']::text[], array['Seafood lovers', 'Date night', 'Family dinner']::text[], array['Vegetarians', 'Budget diners', 'Avoid wait times']::text[], false, '30 min', null, array[]::text[], null, null, 712, 87, 0),
  ('00000000-0000-4000-8000-000000000009', 'new-york-city-carroll-gardens-ugly-baby', 'Ugly Baby', 'New York City', 'Carroll Gardens', 'Thai - Isaan', '$$', 'Brutally spicy southern Thai and Isaan cooking. The fermented fish dishes and raw chili preparations are the real deal — this is not pad see ew territory.', 'Not TikTok Thai — this is real southern Isaan food that most menus water down for NYC', '407 Smith St, Brooklyn, NY 11231', '5pm - 10:30pm Tue-Sun', null, null, array['https://loremflickr.com/400/300/food?lock=uglybaby1', 'https://loremflickr.com/400/300/food?lock=uglybaby2']::text[], 40.6757000, -73.9983000, array['Actually Spicy', 'Authentic Thai', 'Worth the Hype', 'Isaan']::text[], array['actually-spicy', 'local-approved', 'anti-hype', 'date-night']::text[], array['Authentic Thai seekers', 'Spice veterans', 'Adventurous eaters']::text[], array['Kids', 'Heat sensitive', 'Not into fermented flavors']::text[], true, '50 min', 'Ask for "Thai-spicy" and they''ll smirk and actually mean it. The default heat is calibrated for NYC palates.', array['Khao kluk kapi (shrimp paste rice)', 'Sai ua northern Thai sausage', 'Som tum pla ra', 'Crispy catfish salad']::text[], 'Wednesday 5pm sharp — they open, no wait, full menu available', 'trending', 823, 90, 156),
  ('00000000-0000-4000-8000-000000000010', 'new-york-city-jackson-heights-birria-landia', 'Birria-Landia', 'New York City', 'Jackson Heights', 'Mexican - Birria', '$', 'A red cart that became a NYC legend. The birria consommé is rich with dried chilis and the crispy-edged tacos are dipped and griddled to perfection.', '91% of local Latinx food scouts say this is the real birria — not the Instagram tourist version', '76-116 Roosevelt Ave, Jackson Heights, NY 11372', '10am - 11pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=birria1', 'https://loremflickr.com/400/300/food?lock=birria2']::text[], 40.7468000, -73.8912000, array['Birria Tacos', 'Actually Worth It', 'Street Food', 'Late Night']::text[], array['late-night', 'local-approved', 'student-favorites', 'anti-hype']::text[], array['Taco lovers', 'Late-night hunger', 'Budget diners']::text[], array['Vegetarians', 'Need sit-down dining']::text[], true, null, 'Order the quesabirria with extra consommé on the side, not poured over. Dip yourself — it stays crispy that way.', array['Quesabirria (x3)', 'Consommé extra', 'Mulita', 'Birria taco "mojado"']::text[], 'Weeknight 11pm — line moves fast, kitchen is dialed in for the late rush', 'trending', 1089, 91, 198),
  ('00000000-0000-4000-8000-000000000011', 'los-angeles-rosemead-sgv-sea-harbour-seafood-restaurant', 'Sea Harbour Seafood Restaurant', 'Los Angeles', 'Rosemead / SGV', 'Chinese - Cantonese Dim Sum', '$$', 'The definitive SGV dim sum experience. Hong Kong–trained chefs, fresh ingredients daily, and a cart system that rewards those who arrive early.', '95% of Cantonese-speaking locals say this is the best dim sum in SGV — possibly all of North America', '3939 N Rosemead Blvd, Rosemead, CA 91770', '10am - 3pm daily (dim sum), 5pm - 10pm (dinner)', null, null, array['https://loremflickr.com/400/300/food?lock=seaharbour1', 'https://loremflickr.com/400/300/food?lock=seaharbour2']::text[], 34.0618000, -118.0771000, array['Best Dim Sum', 'Culture Approved', 'Cantonese', 'Weekend Ritual']::text[], array['culture-approved', 'local-approved', 'group-dinner']::text[], array['Dim sum lovers', 'Large family groups', 'Weekend brunch']::text[], array['Arrive late (carts empty out)', 'Weekend wait-averse']::text[], false, '60 min weekends', 'Skip the host stand on weekends. Walk straight to the dim sum cart corner near the kitchen — they''ll seat you faster if you look like you know what you''re doing.', array['Har gow', 'Chicken feet in black bean', 'Turnip cake', 'BBQ pork bun', 'Egg tarts (last)']::text[], 'Sunday 11am for the dim sum carts at peak rotation', 'classic', 1876, 93, 167),
  ('00000000-0000-4000-8000-000000000012', 'los-angeles-monterey-park-sgv-noodle-boy', 'Noodle Boy', 'Los Angeles', 'Monterey Park / SGV', 'Chinese - Sichuan Noodles', '$', 'Tiny shop with big flavors. The dan dan mian arrives in a stone bowl with a mouth-numbing Sichuan peppercorn heat that builds beautifully.', 'Sichuan expat community rates this the most authentic dan dan mian outside Chengdu', '318 N Atlantic Blvd, Monterey Park, CA 91754', '11am - 9pm, closed Tuesday', null, null, array['https://loremflickr.com/400/300/food?lock=noodleboy1', 'https://loremflickr.com/400/300/food?lock=noodleboy2']::text[], 34.0598000, -118.1267000, array['Sichuan', 'Actually Spicy', 'Noodles', 'Hidden Gem']::text[], array['actually-spicy', 'hidden-gems', 'student-favorites', 'culture-approved']::text[], array['Sichuan fans', 'Noodle lovers', 'Heat seekers']::text[], array['Heat sensitive', 'Need large portions']::text[], true, null, null, array[]::text[], null, null, 634, 90, 0),
  ('00000000-0000-4000-8000-000000000013', 'los-angeles-koreatown-la-myung-dong-kyoja-la', 'Myung Dong Kyoja LA', 'Los Angeles', 'Koreatown LA', 'Korean - Kalguksu', '$', 'Branch of the iconic Seoul original. Hand-kneaded knife-cut noodles in milky chicken broth. Simple, deeply comforting, and technically flawless.', 'Korean moms in Koreatown LA say the chicken kalguksu is better than back home', '3630 Wilshire Blvd, Los Angeles, CA 90010', '10am - 9:30pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=myungdong1', 'https://loremflickr.com/400/300/food?lock=myungdong2']::text[], 34.0572000, -118.3187000, array['Knife-Cut Noodles', 'Korean', 'Comforting', 'Authentic']::text[], array['local-approved', 'culture-approved', 'student-favorites']::text[], array['Korean food lovers', 'Comfort food seekers', 'Lunch crowds']::text[], array['Spice lovers (mild)', 'Need quick service on weekends']::text[], true, null, null, array[]::text[], null, null, 445, 87, 0),
  ('00000000-0000-4000-8000-000000000014', 'los-angeles-little-tokyo-sushi-gen', 'Sushi Gen', 'Los Angeles', 'Little Tokyo', 'Japanese - Sushi', '$$$', 'A Little Tokyo institution. The sashimi lunch set is legendary for its quality-to-price ratio. Expect a line, expect it to be worth it.', 'Japanese-American community staple since 1980 — the sashimi lunch is one of the best deals in LA', '422 E 2nd St, Los Angeles, CA 90012', '11:15am - 2pm, 5:30pm - 10pm, closed Mon', null, null, array['https://loremflickr.com/400/300/food?lock=sushigen1', 'https://loremflickr.com/400/300/food?lock=sushigen2']::text[], 34.0486000, -118.2405000, array['OG Sushi', 'Japanese Approved', 'Worth the Wait', 'Old School']::text[], array['local-approved', 'culture-approved', 'date-night']::text[], array['Sushi purists', 'Omakase lovers', 'Japanese food seekers']::text[], array['Rushed lunches', 'Prefer trendy spots']::text[], false, '40 min lunch', 'Arrive at 11:00am sharp — they open at 11:15. You''ll be 4th in line instead of 40th. Worth one hour of your morning, not three.', array['Sashimi lunch set', 'Toro nigiri', 'Uni when in season', 'Anago']::text[], 'Tuesday 11am — shortest line of the week', 'classic', 2143, 88, 134),
  ('00000000-0000-4000-8000-000000000015', 'los-angeles-irvine-tasty-noodle-house', 'Tasty Noodle House', 'Los Angeles', 'Irvine', 'Chinese - Taiwanese', '$', 'No-frills Taiwanese comfort food. The braised beef noodle soup has a spiced, slightly sweet red-braised broth that tastes like a Taipei night market.', 'UCI students and Taiwanese families in Irvine all agree — best beef noodle soup in OC', '2750 Alton Pkwy, Irvine, CA 92606', '11am - 11pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=tastynoodle1', 'https://loremflickr.com/400/300/food?lock=tastynoodle2']::text[], 33.6897000, -117.8272000, array['Taiwanese', 'Student Favorite', 'Late Night', 'Beef Noodle']::text[], array['student-favorites', 'late-night', 'culture-approved']::text[], array['Students', 'Late-night cravings', 'Taiwanese food lovers']::text[], array['Need ambiance', 'Weekend parking frustration']::text[], true, null, null, array[]::text[], null, null, 398, 85, 0),
  ('00000000-0000-4000-8000-000000000016', 'los-angeles-alhambra-sgv-chengdu-taste', 'Chengdu Taste', 'Los Angeles', 'Alhambra / SGV', 'Chinese - Sichuan', '$$', 'The aguofei (boiled fish with green Sichuan chilis) will rearrange your entire understanding of fish. The green peppercorn heat is electric and addictive.', 'Sichuan food community consistently votes this best Sichuan in SGV for 5+ years', '828 W Valley Blvd, Alhambra, CA 91803', '11am - 9:30pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=chengdutaste1', 'https://loremflickr.com/400/300/food?lock=chengdutaste2']::text[], 34.0803000, -118.1281000, array['Sichuan', 'Legit Spicy', 'Long Waits', 'Worth It']::text[], array['actually-spicy', 'culture-approved', 'local-approved', 'group-dinner']::text[], array['Sichuan devotees', 'Large groups', 'Heat veterans']::text[], array['Kids', 'Heat sensitive', 'Hate waiting']::text[], true, '60 min', 'Order the aguofei "with extra green peppercorns" — the kitchen will go heavier if you ask in Mandarin. The default is calibrated down.', array['Boiled fish in green peppercorn (aguofei)', 'Toothpick lamb', 'Dry pot cauliflower', 'Mapo tofu']::text[], 'Weekday 4:30pm — beat the wait, ask for the seasonal specials board', 'rising', 1432, 91, 178),
  ('00000000-0000-4000-8000-000000000017', 'los-angeles-chinatown-la-howlin-rays', 'Howlin Rays', 'Los Angeles', 'Chinatown LA', 'American - Nashville Hot Chicken', '$$', 'LA''s best Nashville hot chicken. The heat is genuine, the chicken is perfectly fried, and the bread soaks up the spiced oil into something transcendent.', 'Rare case where the hype is backed up — locals with spice tolerance agree the Howlin level is no joke', '727 N Broadway #128, Los Angeles, CA 90012', '11am - 5pm Wed-Mon', null, null, array['https://loremflickr.com/400/300/food?lock=howlinrays1', 'https://loremflickr.com/400/300/food?lock=howlinrays2']::text[], 34.0584000, -118.2384000, array['Nashville Hot', 'Actually Spicy', 'Worth the Hype', 'Line Food']::text[], array['actually-spicy', 'local-approved', 'anti-hype']::text[], array['Heat lovers', 'Fried chicken fans', 'Casual lunches']::text[], array['Avoid spicy completely', 'Long lunch breaks']::text[], false, null, null, array[]::text[], null, null, 967, 84, 0),
  ('00000000-0000-4000-8000-000000000018', 'los-angeles-west-hollywood-night-market', 'Night + Market', 'Los Angeles', 'West Hollywood', 'Thai - Northern / Street Food', '$$', 'Kris Yenbamroong brings northern Thai street food to LA with no compromises. The sai ua (northern Thai sausage) and khao soi are benchmark-setting.', 'LA Thai community says Chef Kris keeps it real — this is Chiang Mai street food, not Hollywood Thai', '9041 Sunset Blvd, West Hollywood, CA 90069', '5pm - 12am daily', null, null, array['https://loremflickr.com/400/300/food?lock=nightmarket1', 'https://loremflickr.com/400/300/food?lock=nightmarket2']::text[], 34.0904000, -118.3882000, array['Thai Street Food', 'Not TikTok', 'Authentic', 'Late Night']::text[], array['late-night', 'culture-approved', 'anti-hype', 'date-night']::text[], array['Thai food lovers', 'Late-night diners', 'Authentic seekers']::text[], array['Families with kids (loud bar vibe)', 'Vegetarians']::text[], true, null, null, array[]::text[], null, null, 876, 86, 0),
  ('00000000-0000-4000-8000-000000000019', 'bay-area-berkeley-ippuku', 'Ippuku', 'Bay Area', 'Berkeley', 'Japanese - Izakaya', '$$$', 'An izakaya that takes charcoal-grilled yakitori seriously. Binchotan grill, excellent sake and whisky list, and a convivial smoky atmosphere.', 'Japanese expats in the Bay Area call this the most authentic izakaya experience outside Japan', '2130 Center St, Berkeley, CA 94704', '5:30pm - 11pm Tue-Sat', null, null, array['https://loremflickr.com/400/300/food?lock=ippuku1', 'https://loremflickr.com/400/300/food?lock=ippuku2']::text[], 37.8691000, -122.2692000, array['Izakaya', 'Japanese Whisky', 'Yakitori', 'Date Night']::text[], array['culture-approved', 'date-night', 'local-approved']::text[], array['Japanese food lovers', 'Date night', 'Whisky drinkers']::text[], array['Vegetarians', 'Budget diners', 'Loud environments']::text[], true, null, null, array[]::text[], null, null, 743, 88, 0),
  ('00000000-0000-4000-8000-000000000020', 'bay-area-san-francisco-mission-curry-up-now', 'Curry Up Now', 'Bay Area', 'San Francisco - Mission', 'Indian Fusion', '$', 'Indian street food meets SF food truck culture. The deconstructed samosa and tikka masala burritos are genuinely good, not just a gimmick.', 'SF South Asian community voted this best fusion Indian for quality and value', '19 Yerba Buena Ln, San Francisco, CA 94103', '11am - 9pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=curryupnow1', 'https://loremflickr.com/400/300/food?lock=curryupnow2']::text[], 37.7855000, -122.4028000, array['Indian Fusion', 'Quick', 'Vegan Options', 'Wrap']::text[], array['student-favorites', 'local-approved', 'diet-approved']::text[], array['Quick lunch', 'Vegan/vegetarian options', 'Indian flavors']::text[], array['Purists', 'Prefer traditional formats']::text[], true, null, null, array[]::text[], null, null, 512, 82, 0),
  ('00000000-0000-4000-8000-000000000021', 'bay-area-daly-city-koi-palace', 'Koi Palace', 'Bay Area', 'Daly City', 'Chinese - Cantonese Dim Sum', '$$', 'The legendary dim sum destination in the Bay Area. The har gow skin is silky, the turnip cake is crisp outside and custardy within, and the live seafood is impeccable.', '94% of Bay Area Cantonese community members say Koi Palace sets the standard for weekend dim sum', '365 Gellert Blvd, Daly City, CA 94015', '10am - 2:30pm daily (dim sum)', null, null, array['https://loremflickr.com/400/300/food?lock=koipalace1', 'https://loremflickr.com/400/300/food?lock=koipalace2']::text[], 37.6782000, -122.4668000, array['Best Dim Sum', 'Cantonese', 'Family Style', 'Worth the Wait']::text[], array['culture-approved', 'local-approved', 'group-dinner']::text[], array['Dim sum lovers', 'Large families', 'Weekend brunches']::text[], array['Solo diners', 'Hate crowds']::text[], false, '90 min weekends', 'The lobster e-fu noodle is off the dim sum menu — ask the manager directly. Worth blowing the budget once.', array['Har gow', 'Char siu bao', 'Lobster e-fu noodle (off-menu)', 'XO radish cake', 'Egg tarts']::text[], 'Saturday 9:45am — put your name in early, walk to the mall, come back at 10:30', 'classic', 2341, 92, 203),
  ('00000000-0000-4000-8000-000000000022', 'bay-area-fremont-shahi-dine-in', 'Shahi Dine In', 'Bay Area', 'Fremont', 'Indian - Pakistani', '$$', 'Dum biryani cooked the traditional way — sealed pot, slow steam, layered with caramelized onions and whole spices. The lamb biryani is exceptional.', 'Fremont South Asian community calls this the best biryani in the Bay — slow-cooked, not rushed', '39055 Cedar Blvd, Newark, CA 94560', '11am - 10pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=shahidine1', 'https://loremflickr.com/400/300/food?lock=shahidine2']::text[], 37.5296000, -122.0408000, array['Halal', 'Biryani', 'South Asian', 'Family Style']::text[], array['culture-approved', 'diet-approved', 'group-dinner']::text[], array['Halal seekers', 'Biryani fans', 'Family dinners']::text[], array['Non-halal crowd', 'Avoid heavy food']::text[], true, null, null, array[]::text[], null, null, 389, 89, 0),
  ('00000000-0000-4000-8000-000000000023', 'bay-area-oakland-chinatown-vien-huong', 'Vien Huong', 'Bay Area', 'Oakland Chinatown', 'Vietnamese - Chinese', '$', 'A no-nonsense Vietnamese-Chinese breakfast and lunch spot in Oakland Chinatown. The century egg congee and pork chop over rice have fueled Oakland for 40 years.', 'Oakland Vietnamese and Chinese communities eat here every weekend morning — the congee is restorative', '712 Franklin St, Oakland, CA 94607', '7am - 3pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=vienhuong1', 'https://loremflickr.com/400/300/food?lock=vienhuong2']::text[], 37.8022000, -122.2697000, array['Congee', 'Old School', 'Local Institution', 'Cheap Eats']::text[], array['local-approved', 'student-favorites', 'hidden-gems']::text[], array['Early risers', 'Congee lovers', 'Budget diners']::text[], array['Prefer modern cafes', 'Arrive after 1pm (may sell out)']::text[], false, null, null, array[]::text[], null, null, 523, 91, 0),
  ('00000000-0000-4000-8000-000000000024', 'bay-area-milpitas-maruichi-japanese-restaurant', 'Maruichi Japanese Restaurant', 'Bay Area', 'Milpitas', 'Japanese - Ramen', '$', 'The tonkotsu broth is creamy, porcine, and deeply savory. Served with perfectly bouncy chashu pork and thin straight noodles. A Silicon Valley Japanese community staple.', 'Japanese engineers in Silicon Valley say Maruichi is their go-to for tonkotsu — closest to Hakata-style they have found', '170 S Abel St, Milpitas, CA 95035', '11am - 9pm, closed Monday', null, null, array['https://loremflickr.com/400/300/food?lock=maruichi1', 'https://loremflickr.com/400/300/food?lock=maruichi2']::text[], 37.4321000, -121.8989000, array['Ramen', 'Japanese Approved', 'Rich Broth', 'Silicon Valley Staple']::text[], array['culture-approved', 'local-approved', 'student-favorites']::text[], array['Ramen enthusiasts', 'Japanese food lovers', 'Lunch crowds']::text[], array['Vegetarians', 'Late-night eaters']::text[], true, null, null, array[]::text[], null, null, 612, 87, 0),
  ('00000000-0000-4000-8000-000000000025', 'seattle-international-district-tamarind-tree', 'Tamarind Tree', 'Seattle', 'International District', 'Vietnamese', '$$', 'Elevated Vietnamese cuisine in a warm, beautifully decorated space. The pho broth is spiced with star anise and cinnamon in perfect balance, and the bánh xèo is crispy perfection.', 'Seattle Vietnamese community says Tamarind Tree is the rare upscale Vietnamese that keeps it authentic', '1036 S Jackson St, Seattle, WA 98104', '11am - 10pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=tamarindtree1', 'https://loremflickr.com/400/300/food?lock=tamarindtree2']::text[], 47.5993000, -122.3195000, array['Vietnamese', 'Upscale', 'Local Favorite', 'Pho']::text[], array['local-approved', 'culture-approved', 'date-night']::text[], array['Vietnamese food lovers', 'Date night', 'Upscale comfort food']::text[], array['Budget diners', 'Prefer casual vibes']::text[], true, null, null, array[]::text[], null, null, 654, 88, 0),
  ('00000000-0000-4000-8000-000000000026', 'seattle-capitol-hill-kedai-makan', 'Kedai Makan', 'Seattle', 'Capitol Hill', 'Malaysian', '$$', 'A tiny Malaysian gem on Capitol Hill. The nasi lemak comes with sambal made from scratch, perfectly cooked pandan-scented rice, and crispy ikan bilis.', 'Malaysian expat group in Seattle says the nasi lemak is more authentic than most places in Malaysia', '1802 Bellevue Ave, Seattle, WA 98122', '9am - 3pm Wed-Sun', null, null, array['https://loremflickr.com/400/300/food?lock=kedaimakan1', 'https://loremflickr.com/400/300/food?lock=kedaimakan2']::text[], 47.6153000, -122.3241000, array['Malaysian', 'Hidden Gem', 'Nasi Lemak', 'Authentic']::text[], array['hidden-gems', 'culture-approved', 'local-approved']::text[], array['Malaysian food seekers', 'Brunch lovers', 'SE Asian cuisine fans']::text[], array['Dinner seekers (brunch only)', 'Need large group seating']::text[], false, null, null, array[]::text[], null, null, 432, 86, 0),
  ('00000000-0000-4000-8000-000000000027', 'seattle-international-district-pho-bac-sup-shop', 'Pho Bac Sup Shop', 'Seattle', 'International District', 'Vietnamese - Pho', '$', 'The original Pho Bac has been in the ID since 1982. The broth is clear, bright, and aromatic — a testament to simplicity done right for over four decades.', '93% of Seattle Vietnamese community members say Pho Bac has been the gold standard since 1982', '1314 S Jackson St, Seattle, WA 98144', '9am - 9pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=phobacseattle1', 'https://loremflickr.com/400/300/food?lock=phobacseattle2']::text[], 47.5973000, -122.3122000, array['Best Pho Seattle', 'Local Institution', 'Classic', 'Cultural Landmark']::text[], array['local-approved', 'culture-approved', 'student-favorites']::text[], array['Pho purists', 'Budget diners', 'Cultural immersion']::text[], array['Prefer modern interiors', 'Expect elaborate menus']::text[], true, null, null, array[]::text[], null, null, 892, 93, 0),
  ('00000000-0000-4000-8000-000000000028', 'seattle-fremont-revel', 'Revel', 'Seattle', 'Fremont', 'Korean - Modern', '$$$', 'Modern Korean cooking rooted in noodles, dumplings, and pancakes with Pacific Northwest ingredients. The lamb belly rice bowl is a local obsession.', 'Seattle Korean community appreciates how Chef Rachel Yang honors tradition while creating something genuinely new', '403 N 36th St, Seattle, WA 98103', '5pm - 10pm daily, 10am - 2pm Sat-Sun brunch', null, null, array['https://loremflickr.com/400/300/food?lock=revel1', 'https://loremflickr.com/400/300/food?lock=revel2']::text[], 47.6498000, -122.3491000, array['Modern Korean', 'Pacific NW', 'Noodles', 'Worth It']::text[], array['date-night', 'local-approved', 'culture-approved']::text[], array['Modern Korean lovers', 'Date night', 'Brunch weekends']::text[], array['Traditional purists', 'Budget diners']::text[], true, null, null, array[]::text[], null, null, 567, 84, 0),
  ('00000000-0000-4000-8000-000000000029', 'boston-chinatown-boston-gourmet-dumpling-house', 'Gourmet Dumpling House', 'Boston', 'Chinatown Boston', 'Chinese - Shanghainese', '$', 'The go-to for Shanghainese dumplings in Boston. The soup dumplings are reliably good, the scallion pancakes are superbly flaky, and the prices remain refreshingly honest.', 'Boston Chinatown regulars have been coming here for soup dumplings for 15+ years — the consistency is remarkable', '52 Beach St, Boston, MA 02111', '11am - 11pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=gourmetdumpling1', 'https://loremflickr.com/400/300/food?lock=gourmetdumpling2']::text[], 42.3519000, -71.0614000, array['Dumplings', 'XLB', 'Boston Chinatown', 'Local Staple']::text[], array['local-approved', 'student-favorites', 'culture-approved']::text[], array['Dumpling lovers', 'Chinatown exploration', 'Budget diners']::text[], array['Avoid crowds', 'Need fast tables']::text[], true, '20 min', null, array[]::text[], null, null, 723, 88, 0),
  ('00000000-0000-4000-8000-000000000030', 'boston-south-end-myers-chang', 'Myers + Chang', 'Boston', 'South End', 'Asian Fusion', '$$', 'A lively Asian fusion spot that leans into dim sum and street food flavors without being gimmicky. The mapo tofu with crispy pork belly is genuinely excellent.', 'Rare fusion spot where Asian-American community members actually endorse it — the flavors are bold and honest', '1145 Washington St, Boston, MA 02118', '11am - 10pm daily', null, null, array['https://loremflickr.com/400/300/food?lock=myerschang1', 'https://loremflickr.com/400/300/food?lock=myerschang2']::text[], 42.3431000, -71.0678000, array['Asian Fusion', 'Trendy But Good', 'Dim Sum Vibes', 'Cocktails']::text[], array['date-night', 'local-approved', 'group-dinner']::text[], array['Date night', 'Fun group dinners', 'Cocktail lovers']::text[], array['Purists', 'Budget diners']::text[], true, null, null, array[]::text[], null, null, 891, 83, 0),
  ('00000000-0000-4000-8000-000000000031', 'boston-chinatown-boston-penang', 'Penang', 'Boston', 'Chinatown Boston', 'Malaysian', '$', 'Malaysian comfort food in the heart of Boston Chinatown. The curry laksa is rich, coconutty, and fortifying. Late-night hours make it a post-study staple for students.', 'Malaysian students at Boston universities make pilgrimages here for laksa that cuts through New England winters', '685 Washington St, Boston, MA 02111', '11am - 2am daily', null, null, array['https://loremflickr.com/400/300/food?lock=penangboston1', 'https://loremflickr.com/400/300/food?lock=penangboston2']::text[], 42.3534000, -71.0621000, array['Malaysian', 'Laksa', 'Roti', 'Late Night']::text[], array['late-night', 'student-favorites', 'culture-approved']::text[], array['Late-night diners', 'Malaysian food lovers', 'Students']::text[], array['Prefer modern settings']::text[], true, null, null, array[]::text[], null, null, 412, 85, 0),
  ('00000000-0000-4000-8000-000000000032', 'boston-allston-beantown-taqueria', 'Beantown Taqueria', 'Boston', 'Allston', 'Mexican - Tacos', '$', 'A beloved Allston taco shop that does honest al pastor, carnitas, and barbacoa. The salsa bar has genuinely spicy options and the horchata is house-made.', 'Boston college students and Mexican community members both agree — best value tacos in Allston by a mile', '424 Cambridge St, Allston, MA 02134', '11am - 2am daily', null, null, array['https://loremflickr.com/400/300/food?lock=beantowntaqueria1', 'https://loremflickr.com/400/300/food?lock=beantowntaqueria2']::text[], 42.3551000, -71.1293000, array['Tacos', 'Cheap Eats', 'Student Staple', 'Late Night']::text[], array['late-night', 'student-favorites', 'local-approved']::text[], array['Students', 'Late-night hunger', 'Taco lovers', 'Budget diners']::text[], array['Need table service', 'Prefer upscale']::text[], true, null, null, array[]::text[], null, null, 345, 84, 0)
on conflict (slug) do update set
  name = excluded.name,
  city = excluded.city,
  neighborhood = excluded.neighborhood,
  cuisine = excluded.cuisine,
  price = excluded.price,
  description = excluded.description,
  recommendation_reason = excluded.recommendation_reason,
  address = excluded.address,
  hours = excluded.hours,
  phone = excluded.phone,
  website = excluded.website,
  images = excluded.images,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  tags = excluded.tags,
  categories = excluded.categories,
  best_for = excluded.best_for,
  avoid_if = excluded.avoid_if,
  is_open = excluded.is_open,
  wait_time = excluded.wait_time,
  insider_tip = excluded.insider_tip,
  what_locals_order = excluded.what_locals_order,
  best_time_to_go = excluded.best_time_to_go,
  trending_signal = excluded.trending_signal,
  verified_check_ins = excluded.verified_check_ins,
  local_approved_percent = excluded.local_approved_percent,
  recent_visits = excluded.recent_visits,
  updated_at = now();

-- ----------------------------------------------------------------------------
-- Strip fabricated `recommendation_reason` strings.
--
-- The historical seed embedded growth-hack copy like "94% of locals say..."
-- which conflicts with the app's own positioning (no bots, no paid reviews)
-- and would have shown up as production UI text. Real recommendation copy
-- should be derived from actual check-ins; until then NULL is honest.
-- The UI handles null/empty gracefully (transforms.ts: row.recommendation_reason ?? '').
-- ----------------------------------------------------------------------------
update public.restaurants set recommendation_reason = null;
