/**
 * CraveMap — Restaurant Seed Script
 * Seeds all 32 mock restaurants into the Supabase `restaurants` table.
 *
 * Usage:
 *   SERVICE_ROLE_KEY="sb_secret_..." node supabase/seed/seed_restaurants.mjs
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '../../');

function loadEnv() {
  try {
    const env = readFileSync(join(root, '.env'), 'utf8');
    for (const line of env.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const [key, ...rest] = trimmed.split('=');
      if (key && rest.length) process.env[key.trim()] = rest.join('=').trim();
    }
  } catch { /* no .env */ }
}
loadEnv();

const SUPABASE_URL     = process.env.EXPO_PUBLIC_SUPABASE_URL?.replace(/\/$/, '');
const SERVICE_ROLE_KEY = process.env.SERVICE_ROLE_KEY;

if (!SUPABASE_URL) { console.error('❌  EXPO_PUBLIC_SUPABASE_URL not set'); process.exit(1); }
if (!SERVICE_ROLE_KEY) { console.error('❌  SERVICE_ROLE_KEY not set'); process.exit(1); }

// ── Restaurant data ────────────────────────────────────────────────────────
const restaurants = [
  // ── NYC ──────────────────────────────────────────────────────────────────
  {
    slug: 'xian-famous-foods-flushing', name: "Xi'an Famous Foods",
    city: 'New York City', neighborhood: 'Flushing', cuisine: 'Chinese - Shaanxi', price: '$',
    description: 'Hand-pulled noodles from Shaanxi province. The biangbiang noodles are wide, chewy, and dressed in chili oil.',
    recommendation_reason: '94% of people with your taste say the spicy cumin lamb noodles are the real deal',
    address: '133-31 39th Ave, Flushing, NY 11354', hours: '11am - 9pm daily', phone: '+1 718-888-6628',
    images: ['https://picsum.photos/seed/xianfoods1/400/300','https://picsum.photos/seed/xianfoods2/400/300'],
    latitude: 40.7580, longitude: -73.8303,
    tags: ['Actually Worth It','Local Favorite','Spicy','Authentic'],
    categories: ['local-approved','actually-spicy','hidden-gems','student-favorites'],
    best_for: ['Spice lovers','Noodle enthusiasts','Authentic Chinese food'],
    avoid_if: ['Sensitive to heat','Prefer fusion','Need lots of seating'],
    is_open: true, wait_time: '10 min',
    insider_tip: 'Ask for the noodles "extra al dente" — they\'ll pull a fresh batch. Game changer.',
    what_locals_order: ['Biangbiang noodles in chili oil','Stewed cumin lamb noodles','Tiger vegetables','Spicy & tingly beef'],
    best_time_to_go: 'Weekday 2pm — empty, fresh noodle batch',
    trending_signal: 'classic', verified_check_ins: 847, local_approved_percent: 91, recent_visits: 142,
  },
  {
    slug: 'nan-xiang-xiao-long-bao-flushing', name: 'Nan Xiang Xiao Long Bao',
    city: 'New York City', neighborhood: 'Flushing', cuisine: 'Chinese - Shanghainese', price: '$$',
    description: 'The gold standard for soup dumplings in Flushing. Thin skin, rich broth, perfectly portioned pork filling.',
    recommendation_reason: 'Best XLB in NYC per 89% of local food scouts in your area',
    address: '38-12 Prince St, Flushing, NY 11354', hours: '10:30am - 10pm daily', phone: null,
    images: ['https://picsum.photos/seed/nanxiang1/400/300','https://picsum.photos/seed/nanxiang2/400/300'],
    latitude: 40.7593, longitude: -73.8314,
    tags: ['Soup Dumplings','Local Favorite','Worth the Wait'],
    categories: ['local-approved','culture-approved','group-dinner'],
    best_for: ['Dumpling fans','Date night','Group dinner'],
    avoid_if: ['Hate crowds','Need fast service','Not into pork'],
    is_open: true, wait_time: '25 min',
    insider_tip: 'Put your name down, walk to New World Mall next door. They\'ll text you.',
    what_locals_order: ['Pork XLB (2 steamers)','Crab roe XLB (seasonal)','Pan-fried buns','Wood ear with vinegar'],
    best_time_to_go: 'Sunday 10:30am — first steamers of the day, shortest wait',
    trending_signal: 'classic', verified_check_ins: 1203, local_approved_percent: 89, recent_visits: 187,
  },
  {
    slug: 'white-bear-flushing', name: 'White Bear',
    city: 'New York City', neighborhood: 'Flushing', cuisine: 'Chinese - Dumplings', price: '$',
    description: 'A cash-only counter with no English menu and no sign. Order the #6 — pork and chive wontons in chili oil.',
    recommendation_reason: 'No sign, no menu in English, no Instagram — just the best wontons in NYC',
    address: '135-02 Roosevelt Ave, Flushing, NY 11354', hours: '8am - 9pm daily', phone: null,
    images: ['https://picsum.photos/seed/whitebear1/400/300','https://picsum.photos/seed/whitebear2/400/300'],
    latitude: 40.7561, longitude: -73.8296,
    tags: ['Hidden Gem','Locals Only','Cash Only','No Sign'],
    categories: ['hidden-gems','local-approved','student-favorites','culture-approved'],
    best_for: ['Adventurous eaters','Authentic Chinese','Budget diners'],
    avoid_if: ['Need English menu','Prefer cards','Want ambiance'],
    is_open: true, wait_time: null,
    insider_tip: 'Bring small bills. Order by pointing at #6 and holding up fingers.',
    what_locals_order: ['#6 pork & chive wontons in chili oil','Beef noodle soup','Pork & cabbage dumplings'],
    best_time_to_go: 'Tuesday or Wednesday 3pm — no line, fresh wontons',
    trending_signal: 'underrated', verified_check_ins: 621, local_approved_percent: 95, recent_visits: 78,
  },
  {
    slug: 'kang-ho-dong-baekjeong-nyc', name: 'Kang Ho Dong Baekjeong',
    city: 'New York City', neighborhood: 'Koreatown', cuisine: 'Korean BBQ', price: '$$$',
    description: 'High-energy KBBQ in K-town. The brisket melts perfectly over the domed grill and the egg soufflé is worth the hype.',
    recommendation_reason: 'Top-rated KBBQ in NYC by 88% of locals who know their meat',
    address: '1 E 32nd St, New York, NY 10016', hours: '11:30am - 12am daily', phone: null,
    images: ['https://picsum.photos/seed/kbbq1/400/300','https://picsum.photos/seed/kbbq2/400/300'],
    latitude: 40.7474, longitude: -73.9868,
    tags: ['Korean BBQ','Group Favorite','Late Night','Worth It'],
    categories: ['group-dinner','local-approved','date-night'],
    best_for: ['Group celebrations','Meat lovers','Late night'],
    avoid_if: ['Vegetarians','Quiet dinner','Budget-conscious'],
    is_open: true, wait_time: '40 min',
    insider_tip: 'Go to the 2nd floor — less chaotic, same kitchen. Ask for the egg soufflé starter.',
    what_locals_order: ['Brisket (chadolbaegi)','Pork belly (samgyeopsal)','Egg soufflé','Doenjang jjigae'],
    best_time_to_go: 'Weekday lunch — 30% cheaper and no wait',
    trending_signal: 'trending', verified_check_ins: 934, local_approved_percent: 88, recent_visits: 203,
  },
  {
    slug: 'haidilao-times-square', name: 'Haidilao Hot Pot',
    city: 'New York City', neighborhood: 'Midtown', cuisine: 'Chinese - Hot Pot', price: '$$$',
    description: "China's most famous hot pot chain, legendary for over-the-top service — noodles made tableside while you wait.",
    recommendation_reason: '85% of hot pot fans say the Sichuan broth + unlimited condiment bar is unmatched',
    address: '39 W 32nd St, New York, NY 10001', hours: '11am - 2am daily', phone: null,
    images: ['https://picsum.photos/seed/haidilao1/400/300','https://picsum.photos/seed/haidilao2/400/300'],
    latitude: 40.7480, longitude: -73.9877,
    tags: ['Hot Pot','Group Dinner','Worth It','Spicy'],
    categories: ['group-dinner','culture-approved','actually-spicy'],
    best_for: ['Large groups','Special occasions','Spice lovers'],
    avoid_if: ['Solo dining','Quick meal','Light eaters'],
    is_open: true, wait_time: '1 hr',
    insider_tip: 'Download the app and queue remotely. Order the "mashed potato" as a dessert — trust.',
    what_locals_order: ['Sichuan spicy broth','Wagyu beef slices','Hand-made noodles','Brain tofu'],
    best_time_to_go: 'Late Sunday night — surprisingly low wait after 10pm',
    trending_signal: 'rising', verified_check_ins: 1456, local_approved_percent: 85, recent_visits: 312,
  },
  {
    slug: 'biang-biang-nyc', name: 'Biang! Biang! Noodles',
    city: 'New York City', neighborhood: 'East Village', cuisine: 'Chinese - Shaanxi', price: '$',
    description: 'Named for the sound the dough makes when slapped against the counter. Belt noodles, 3 inches wide, aggressively sauced.',
    recommendation_reason: 'Best biangbiang noodles in Manhattan per the Chinese food community',
    address: '157 2nd Ave, New York, NY 10003', hours: '12pm - 10pm, closed Tuesdays', phone: null,
    images: ['https://picsum.photos/seed/biangbiang1/400/300','https://picsum.photos/seed/biangbiang2/400/300'],
    latitude: 40.7267, longitude: -73.9870,
    tags: ['Belt Noodles','Under the Radar','Spicy','Authentic'],
    categories: ['hidden-gems','actually-spicy','student-favorites'],
    best_for: ['Noodle obsessives','Spicy food fans','Solo diners'],
    avoid_if: ['Heat-sensitive','Prefer polished ambiance'],
    is_open: true, wait_time: null,
    insider_tip: 'Get the "dry mixed" style, not the soup. The chili oil hits differently.',
    what_locals_order: ['Hand-ripped belt noodles','Spicy lamb noodles','Garlic cucumber salad'],
    best_time_to_go: 'Weekday 1pm — no line, fresh noodles',
    trending_signal: 'underrated', verified_check_ins: 389, local_approved_percent: 93, recent_visits: 56,
  },
  {
    slug: 'hop-kee-chinatown', name: 'Hop Kee Restaurant',
    city: 'New York City', neighborhood: 'Chinatown', cuisine: 'Chinese - Cantonese', price: '$',
    description: 'An underground Cantonese restaurant open since 1968. The salted fish fried rice is the best version in NYC.',
    recommendation_reason: '89% of Chinatown regulars call Hop Kee the most reliable old-school Cantonese in Manhattan',
    address: '21 Mott St, New York, NY 10013', hours: '11am - 11pm, closed Tuesdays', phone: null,
    images: ['https://picsum.photos/seed/hopkee1/400/300','https://picsum.photos/seed/hopkee2/400/300'],
    latitude: 40.7145, longitude: -73.9988,
    tags: ['Old School','Underground','Cantonese','Chinatown Classic'],
    categories: ['culture-approved','local-approved','hidden-gems'],
    best_for: ['History seekers','Cantonese food lovers','Authentic seekers'],
    avoid_if: ['Need modern ambiance','Want Instagram-friendly food'],
    is_open: true, wait_time: null,
    insider_tip: 'Walk down the stairs to the basement entrance. Cash preferred.',
    what_locals_order: ['Salted fish & chicken fried rice','Steamed whole fish','Beef with bitter melon','Sautéed water spinach'],
    best_time_to_go: 'Weeknight 7pm — regulars only, no tourists',
    trending_signal: 'classic', verified_check_ins: 423, local_approved_percent: 89, recent_visits: 71,
  },
  {
    slug: 'spicy-village-nyc', name: 'Spicy Village',
    city: 'New York City', neighborhood: 'Chinatown', cuisine: 'Chinese - Henan', price: '$',
    description: 'The "big tray chicken" (大盘鸡) — a whole cut-up chicken braised in chili oil, potatoes, and wide noodles.',
    recommendation_reason: 'The single most unique dish in NYC Chinatown per the local food community',
    address: '68 Forsyth St, New York, NY 10002', hours: '11am - 10pm daily', phone: null,
    images: ['https://picsum.photos/seed/spicyvillage1/400/300','https://picsum.photos/seed/spicyvillage2/400/300'],
    latitude: 40.7161, longitude: -73.9952,
    tags: ['Big Tray Chicken','Unique','Henan','Must Try'],
    categories: ['hidden-gems','culture-approved','local-approved','actually-spicy'],
    best_for: ['Adventurous eaters','Groups of 2-4','Unique experiences'],
    avoid_if: ['Spice-free required','Solo dining'],
    is_open: true, wait_time: null,
    insider_tip: 'The noodles come after the chicken — make sure to order them.',
    what_locals_order: ['Big tray chicken (大盘鸡)','Hand-pulled noodles','Lamb skewers','Cucumber salad'],
    best_time_to_go: 'Weekday 12:30pm — freshest chicken, minimal wait',
    trending_signal: 'trending', verified_check_ins: 678, local_approved_percent: 96, recent_visits: 123,
  },
  {
    slug: 'golden-shopping-mall-flushing', name: 'Golden Shopping Mall Food Court',
    city: 'New York City', neighborhood: 'Flushing', cuisine: 'Chinese - Mixed', price: '$',
    description: 'A basement food court with 20+ stalls selling regional Chinese cuisines you cannot find above ground.',
    recommendation_reason: 'Unanimously called the most authentic regional Chinese food court in the US',
    address: '41-28 Main St, Flushing, NY 11355', hours: '10am - 10pm daily', phone: null,
    images: ['https://picsum.photos/seed/goldenmall1/400/300','https://picsum.photos/seed/goldenmall2/400/300'],
    latitude: 40.7595, longitude: -73.8305,
    tags: ['Food Court','Regional Chinese','Hidden Underground','No Frills'],
    categories: ['hidden-gems','student-favorites','culture-approved','local-approved'],
    best_for: ['Chinese food explorers','Budget diners','Groups'],
    avoid_if: ['Need table service','Want English menus'],
    is_open: true, wait_time: null,
    insider_tip: 'Walk every stall before ordering. The lamb skewer stall in the back left corner is why you are here.',
    what_locals_order: ['Lamb skewers (Xinjiang style)','Chongqing spicy noodles','Jianbing','Stinky tofu','Scallion pancake'],
    best_time_to_go: 'Saturday 2pm — post-lunch rush, every stall still open',
    trending_signal: 'underrated', verified_check_ins: 934, local_approved_percent: 97, recent_visits: 201,
  },
  // ── LA ───────────────────────────────────────────────────────────────────
  {
    slug: 'jjamppong-house-la', name: 'Jjamppong House',
    city: 'Los Angeles', neighborhood: 'Koreatown', cuisine: 'Korean', price: '$$',
    description: 'Fiery seafood noodle soup that will make you sweat and order another bowl. Broth built over 6 hours.',
    recommendation_reason: '91% of spice-lovers say this is the best jjamppong in LA',
    address: '3355 W Olympic Blvd, Los Angeles, CA 90019', hours: '11am - 9:30pm, closed Mondays', phone: null,
    images: ['https://picsum.photos/seed/jjamppong1/400/300','https://picsum.photos/seed/jjamppong2/400/300'],
    latitude: 34.0220, longitude: -118.3321,
    tags: ['Seafood Noodles','Extremely Spicy','Local Cult','Hidden Gem'],
    categories: ['actually-spicy','hidden-gems','local-approved'],
    best_for: ['Spice extremists','Seafood lovers','Noodle fans'],
    avoid_if: ['Low heat tolerance','Shellfish allergic','Light eaters'],
    is_open: true, wait_time: null,
    insider_tip: 'Ask for "mild" spice — it still has a solid kick. Normal is aggressive.',
    what_locals_order: ['Jjamppong (original spicy)','Pork cutlet combo','Fried dumplings'],
    best_time_to_go: 'Tuesday lunch — freshest seafood delivery day',
    trending_signal: 'underrated', verified_check_ins: 445, local_approved_percent: 91, recent_visits: 62,
  },
  {
    slug: 'phoenix-bakery-la', name: 'Phoenix Bakery',
    city: 'Los Angeles', neighborhood: 'Chinatown', cuisine: 'Chinese - Bakery', price: '$',
    description: 'Open since 1938. The strawberry cream cake is the most famous in Chinatown. Cash only, line always.',
    recommendation_reason: 'A genuine LA institution — 87% of locals say this is a must-visit',
    address: '969 N Broadway, Los Angeles, CA 90012', hours: '8am - 6pm daily', phone: null,
    images: ['https://picsum.photos/seed/phoenix1/400/300','https://picsum.photos/seed/phoenix2/400/300'],
    latitude: 34.0635, longitude: -118.2368,
    tags: ['Historic','Cash Only','Bakery','Local Institution'],
    categories: ['culture-approved','local-approved','student-favorites'],
    best_for: ['History buffs','Bakery fans','Gift-buyers'],
    avoid_if: ['Need cards','Dislike sweet','Hate lines'],
    is_open: true, wait_time: null,
    insider_tip: 'Call ahead to order a whole strawberry cream cake.',
    what_locals_order: ['Strawberry cream cake','Almond cookies','Cocktail buns','Taro rolls'],
    best_time_to_go: 'Weekday morning when the almond cookies come out fresh',
    trending_signal: 'classic', verified_check_ins: 567, local_approved_percent: 87, recent_visits: 94,
  },
  {
    slug: 'yang-chow-la', name: 'Yang Chow Restaurant',
    city: 'Los Angeles', neighborhood: 'Chinatown', cuisine: 'Chinese - Cantonese', price: '$$',
    description: "The slippery shrimp at Yang Chow is a cult dish — sweet, walnut-y, slightly spicy. Locals have been ordering it since 1977.",
    recommendation_reason: "LA's most beloved Chinese-American restaurant. The slippery shrimp is worth the trip.",
    address: '819 N Broadway, Los Angeles, CA 90012', hours: '11:30am - 9:30pm daily', phone: null,
    images: ['https://picsum.photos/seed/yangchow1/400/300','https://picsum.photos/seed/yangchow2/400/300'],
    latitude: 34.0617, longitude: -118.2375,
    tags: ['Cult Dish','Local Institution','Family Style','Nostalgic'],
    categories: ['culture-approved','local-approved','group-dinner'],
    best_for: ['Group dining','Nostalgia seekers','First-timers to Chinatown'],
    avoid_if: ['Shrimp allergic','Want trendy vibes'],
    is_open: true, wait_time: null,
    insider_tip: 'Order two portions of slippery shrimp minimum. One is not enough for a table of 4.',
    what_locals_order: ['Slippery shrimp','Pork fried rice','Beef with broccoli','Egg flower soup'],
    best_time_to_go: 'Early Sunday dinner — families just left, kitchen is fresh',
    trending_signal: 'classic', verified_check_ins: 734, local_approved_percent: 86, recent_visits: 128,
  },
  {
    slug: 'lunasia-dim-sum-la', name: 'Lunasia Dim Sum House',
    city: 'Los Angeles', neighborhood: 'Alhambra', cuisine: 'Chinese - Dim Sum', price: '$$',
    description: 'Upscale dim sum with iPad ordering and zero carts. The har gow skin is paper-thin, the XLB exceptional.',
    recommendation_reason: '92% of dim sum regulars say this is the best in the SGV',
    address: '500 W Main St, Alhambra, CA 91801', hours: '10am - 3pm, 5pm - 9:30pm daily', phone: null,
    images: ['https://picsum.photos/seed/lunasia1/400/300','https://picsum.photos/seed/lunasia2/400/300'],
    latitude: 34.0953, longitude: -118.1270,
    tags: ['Dim Sum','Upscale','No Carts','SGV Best'],
    categories: ['local-approved','culture-approved','group-dinner'],
    best_for: ['Dim sum purists','Group brunch','Family meals'],
    avoid_if: ['On a tight budget','Prefer cart service nostalgia'],
    is_open: true, wait_time: '30 min weekends',
    insider_tip: 'Reserve 2 weeks ahead for weekends. Order the snow crab dumplings if seasonal.',
    what_locals_order: ['Har gow','Siu mai','Char siu bao','Snow crab dumplings','Mango pudding'],
    best_time_to_go: 'Weekday 11am — no wait, unhurried service',
    trending_signal: 'trending', verified_check_ins: 892, local_approved_percent: 92, recent_visits: 167,
  },
  {
    slug: 'newport-seafood-la', name: 'Newport Seafood Restaurant',
    city: 'Los Angeles', neighborhood: 'San Gabriel', cuisine: 'Chinese - Cantonese Seafood', price: '$$$',
    description: 'Order the live lobster prepared Hong Kong style. The salt and pepper crab is legendary.',
    recommendation_reason: '90% of Cantonese seafood lovers rank this their #1 in LA',
    address: '518 W Las Tunas Dr, San Gabriel, CA 91776', hours: '11am - 11pm daily', phone: null,
    images: ['https://picsum.photos/seed/newport1/400/300','https://picsum.photos/seed/newport2/400/300'],
    latitude: 34.0997, longitude: -118.1055,
    tags: ['Live Seafood','Special Occasion','Hong Kong Style','Family Favorite'],
    categories: ['local-approved','culture-approved','group-dinner'],
    best_for: ['Seafood lovers','Special occasions','Large groups'],
    avoid_if: ['Shellfish allergic','Budget dining','Solo meals'],
    is_open: true, wait_time: null,
    insider_tip: 'Come for the live seafood in tanks at the entrance. Pick your creature, they price by weight.',
    what_locals_order: ['Salt & pepper lobster','Peking duck (call ahead)','Steamed fish','Fried rice in lotus leaf'],
    best_time_to_go: 'Weekday dinner — full menu, calmer service',
    trending_signal: 'classic', verified_check_ins: 678, local_approved_percent: 90, recent_visits: 143,
  },
  // ── Bay Area ─────────────────────────────────────────────────────────────
  {
    slug: 'hong-kong-lounge-ii-sf', name: 'Hong Kong Lounge II',
    city: 'Bay Area', neighborhood: 'Richmond District', cuisine: 'Chinese - Dim Sum', price: '$$',
    description: 'Cart service dim sum in the Sunset. The shrimp rice rolls are silky, the pineapple buns legendary.',
    recommendation_reason: '93% of SF locals call this the best traditional dim sum in the city',
    address: '3300 Geary Blvd, San Francisco, CA 94118', hours: '10am - 2:30pm, 5pm - 9pm daily', phone: null,
    images: ['https://picsum.photos/seed/hklounge1/400/300','https://picsum.photos/seed/hklounge2/400/300'],
    latitude: 37.7805, longitude: -122.4566,
    tags: ['Cart Service','Old School','Locals Only','Worth the Wait'],
    categories: ['local-approved','culture-approved','group-dinner'],
    best_for: ['Dim sum traditionalists','Families','Weekend brunch'],
    avoid_if: ['Need fast service','Vegetarian'],
    is_open: true, wait_time: '45 min weekends',
    insider_tip: 'Go at 10am sharp when doors open. By 10:30 the wait is 45 minutes.',
    what_locals_order: ['Har gow','Rice noodle rolls (cheung fun)','Chicken feet','Turnip cake','Pineapple bun'],
    best_time_to_go: 'Weekday 10:30am — all carts out, no line',
    trending_signal: 'classic', verified_check_ins: 781, local_approved_percent: 93, recent_visits: 156,
  },
  {
    slug: 'dragon-beaux-sf', name: 'Dragon Beaux',
    city: 'Bay Area', neighborhood: 'Richmond District', cuisine: 'Chinese - Dim Sum', price: '$$$',
    description: 'The most Instagram-worthy dim sum in SF. Colorful dumplings shaped like goldfish — taste matches the looks.',
    recommendation_reason: 'Highest-rated upscale dim sum in SF per taste-match criteria',
    address: '5700 Geary Blvd, San Francisco, CA 94121', hours: '10am - 3pm, 5pm - 10pm daily', phone: null,
    images: ['https://picsum.photos/seed/dragonbeaux1/400/300','https://picsum.photos/seed/dragonbeaux2/400/300'],
    latitude: 37.7802, longitude: -122.4753,
    tags: ['Instagrammable','Upscale Dim Sum','Colorful','Worth It'],
    categories: ['local-approved','date-night','group-dinner'],
    best_for: ['Special occasions','Dim sum lovers','Groups'],
    avoid_if: ['Hate crowds','Strict budget'],
    is_open: true, wait_time: null,
    insider_tip: 'Book 2 weeks ahead on OpenTable. The "5 colored dumplings" are the must-order.',
    what_locals_order: ['5 colored crystal dumplings','Lobster XLB','Peking duck bun','Black truffle siu mai'],
    best_time_to_go: 'Weekday lunch — less crowded, same menu',
    trending_signal: 'trending', verified_check_ins: 923, local_approved_percent: 88, recent_visits: 198,
  },
  {
    slug: 'old-mandarin-islamic-sf', name: 'Old Mandarin Islamic Restaurant',
    city: 'Bay Area', neighborhood: 'Sunset District', cuisine: 'Chinese - Halal', price: '$',
    description: 'The only proper Halal Chinese restaurant in SF. Lamb skewers charred perfectly, hand-pulled noodles as good as Beijing.',
    recommendation_reason: 'Unanimously loved by locals — 96% approval from SF Chinese community',
    address: '3132 Vicente St, San Francisco, CA 94116', hours: '11am - 9:30pm, closed Tuesdays', phone: null,
    images: ['https://picsum.photos/seed/oldmandarin1/400/300','https://picsum.photos/seed/oldmandarin2/400/300'],
    latitude: 37.7393, longitude: -122.4822,
    tags: ['Halal','Hidden Gem','Lamb','Authentic Northern Chinese'],
    categories: ['hidden-gems','culture-approved','local-approved'],
    best_for: ['Halal food seekers','Lamb lovers','Authentic seekers'],
    avoid_if: ['Pork required','Vegetarian (limited options)'],
    is_open: true, wait_time: null,
    insider_tip: 'BYOB — no corkage fee. The lamb hot pot (in winter) is secret menu; ask for it.',
    what_locals_order: ['Lamb skewers','Hand-pulled beef noodle soup','Scallion pancake','Stir-fried lamb with green onion'],
    best_time_to_go: 'Wednesday dinner — post-delivery day, fresh lamb',
    trending_signal: 'underrated', verified_check_ins: 312, local_approved_percent: 96, recent_visits: 43,
  },
  {
    slug: 'koi-palace-daly-city', name: 'Koi Palace',
    city: 'Bay Area', neighborhood: 'Daly City', cuisine: 'Chinese - Dim Sum & Seafood', price: '$$$',
    description: 'The gold standard for dim sum in the Bay Area. XLB made to order, salt and pepper squid the best anywhere.',
    recommendation_reason: '94% of Bay Area dim sum lovers say Koi Palace is still the top',
    address: '365 Gellert Blvd, Daly City, CA 94015', hours: '10am - 2pm, 5pm - 9pm; 9am - 9pm weekends', phone: null,
    images: ['https://picsum.photos/seed/koipalace1/400/300','https://picsum.photos/seed/koipalace2/400/300'],
    latitude: 37.6879, longitude: -122.4717,
    tags: ['Top Rated','Dim Sum','Live Seafood','Must Visit'],
    categories: ['local-approved','culture-approved','group-dinner'],
    best_for: ['Dim sum pilgrims','Seafood lovers','Family celebrations'],
    avoid_if: ['Casual dining only','Very tight budget'],
    is_open: true, wait_time: '1 hr weekends',
    insider_tip: 'Arrive 30 min before opening on weekends. There will be a line. It moves fast.',
    what_locals_order: ['Pan-fried XLB','Salt & pepper squid','Egg tarts','Roast duck','Durian mochi'],
    best_time_to_go: 'Weekday 11am — minimal wait, attentive service',
    trending_signal: 'classic', verified_check_ins: 1678, local_approved_percent: 94, recent_visits: 287,
  },
  {
    slug: 'iyasare-berkeley', name: 'Iyasare',
    city: 'Bay Area', neighborhood: 'Berkeley', cuisine: 'Japanese', price: '$$$',
    description: 'Upscale Japanese comfort food in Berkeley with a serious sake program.',
    recommendation_reason: '89% of Berkeley locals say this is the best Japanese restaurant in the East Bay',
    address: '1830 4th St, Berkeley, CA 94710', hours: '5pm - 9:30pm Tue–Sun', phone: null,
    images: ['https://picsum.photos/seed/iyasare1/400/300','https://picsum.photos/seed/iyasare2/400/300'],
    latitude: 37.8667, longitude: -122.3022,
    tags: ['Upscale','Sake','Japanese','Date Night'],
    categories: ['date-night','local-approved'],
    best_for: ['Date night','Japanese food lovers','Sake enthusiasts'],
    avoid_if: ['Looking for cheap eats','Want sushi (cooked food only)'],
    is_open: true, wait_time: null,
    insider_tip: 'Sit at the bar and ask the bartender to pair sake with each dish.',
    what_locals_order: ['Wagyu beef tataki','Grilled black cod','Seasonal mushroom dish','Yuzu sorbet'],
    best_time_to_go: 'Wednesday 6pm — quietest night, most attentive service',
    trending_signal: 'rising', verified_check_ins: 456, local_approved_percent: 89, recent_visits: 87,
  },
  // ── Seattle ───────────────────────────────────────────────────────────────
  {
    slug: 'tamarind-tree-seattle', name: 'Tamarind Tree',
    city: 'Seattle', neighborhood: 'International District', cuisine: 'Vietnamese', price: '$$',
    description: 'The most beautiful Vietnamese restaurant in Seattle. The lemongrass prawns are extraordinary.',
    recommendation_reason: '92% of Vietnamese food fans in Seattle say this is unmissable',
    address: '1036 S Jackson St, Seattle, WA 98104', hours: '11am - 10pm daily', phone: null,
    images: ['https://picsum.photos/seed/tamarindtree1/400/300','https://picsum.photos/seed/tamarindtree2/400/300'],
    latitude: 47.5979, longitude: -122.3169,
    tags: ['Beautiful Space','Vietnamese','Local Gem','Worth It'],
    categories: ['local-approved','date-night','group-dinner'],
    best_for: ['Date nights','Groups','Vietnamese food lovers'],
    avoid_if: ['Tight budget','Want super traditional pho'],
    is_open: true, wait_time: null,
    insider_tip: 'Come for the banh hoi — rice vermicelli plates you assemble yourself.',
    what_locals_order: ['Lemongrass prawns','Banh hoi platter','Cơm tấm','Vietnamese iced coffee'],
    best_time_to_go: 'Weekday dinner — reservation not needed, full menu',
    trending_signal: 'classic', verified_check_ins: 567, local_approved_percent: 92, recent_visits: 98,
  },
  {
    slug: 'jade-garden-seattle', name: 'Jade Garden',
    city: 'Seattle', neighborhood: 'International District', cuisine: 'Chinese - Dim Sum', price: '$',
    description: 'Cash-only, cart-service dim sum that locals have been eating since 1982. Lines wrap around the block on weekends.',
    recommendation_reason: '94% of Seattle dim sum fans say there is no substitute for Jade Garden',
    address: '424 7th Ave S, Seattle, WA 98104', hours: '9am - 2pm weekends; 10am - 2pm weekdays', phone: null,
    images: ['https://picsum.photos/seed/jadegarden1/400/300','https://picsum.photos/seed/jadegarden2/400/300'],
    latitude: 47.5967, longitude: -122.3243,
    tags: ['Cash Only','Old School','Cart Service','Institution'],
    categories: ['local-approved','culture-approved','student-favorites'],
    best_for: ['Dim sum lovers','Cash-friendly diners','Early birds'],
    avoid_if: ['Need cards','Hate waits','Vegetarian'],
    is_open: true, wait_time: '50 min weekends',
    insider_tip: 'Get there at 9am or accept your fate in line. The taro puffs sell out first.',
    what_locals_order: ['Taro puffs (wu gok)','Shrimp dumplings (har gow)','Sticky rice in lotus leaf','Egg tarts'],
    best_time_to_go: '9am sharp Saturday — zero wait, hottest food',
    trending_signal: 'classic', verified_check_ins: 812, local_approved_percent: 94, recent_visits: 178,
  },
  {
    slug: 'little-uncle-seattle', name: 'Little Uncle',
    city: 'Seattle', neighborhood: 'Capitol Hill', cuisine: 'Thai', price: '$',
    description: 'Counter-service Thai food so good it has a cult following. The khao man gai is made with 24-hour stock.',
    recommendation_reason: '91% of Capitol Hill regulars say this is the best casual Thai in Seattle',
    address: '1523 E Madison St, Seattle, WA 98122', hours: '11am - 9pm, closed Sundays', phone: null,
    images: ['https://picsum.photos/seed/littleuncle1/400/300','https://picsum.photos/seed/littleuncle2/400/300'],
    latitude: 47.6151, longitude: -122.3089,
    tags: ['Cult Following','Thai','Counter Service','Authentic'],
    categories: ['hidden-gems','local-approved','student-favorites'],
    best_for: ['Thai food seekers','Solo diners','Lunch crowds'],
    avoid_if: ['Need table service','Large groups'],
    is_open: true, wait_time: null,
    insider_tip: 'The khao man gai sells out. Go before 1pm.',
    what_locals_order: ['Khao man gai','Boat noodles (kuaytiaw ruea)','Mango sticky rice','Thai iced tea'],
    best_time_to_go: '11:30am Monday — freshest start to the week, no wait',
    trending_signal: 'underrated', verified_check_ins: 423, local_approved_percent: 91, recent_visits: 67,
  },
  {
    slug: 'fuji-sushi-seattle', name: 'Fuji Sushi',
    city: 'Seattle', neighborhood: 'International District', cuisine: 'Japanese - Sushi', price: '$$',
    description: 'The unpretentious counter sushi bar old-school Seattle swears by. Nigiri cut by someone doing it for 30 years.',
    recommendation_reason: '88% of Seattle sushi fans say Fuji is the most honest fish in the city',
    address: '520 S Main St, Seattle, WA 98104', hours: '11:30am - 10pm Tue–Sat', phone: null,
    images: ['https://picsum.photos/seed/fujisushi1/400/300','https://picsum.photos/seed/fujisushi2/400/300'],
    latitude: 47.5987, longitude: -122.3242,
    tags: ['Old School','Honest Sushi','Counter Seating','Local Staple'],
    categories: ['local-approved','culture-approved','date-night'],
    best_for: ['Sushi purists','Counter dining lovers','Fish quality seekers'],
    avoid_if: ['Want flashy rolls','Need lots of seats'],
    is_open: true, wait_time: null,
    insider_tip: 'Sit at the counter and let the chef choose your omakase. Tell him your budget.',
    what_locals_order: ['Omakase (counter only)','Salmon nigiri','Albacore tataki','Uni (in season)'],
    best_time_to_go: 'Thursday 6pm — quietest weeknight, chef in best mood',
    trending_signal: 'classic', verified_check_ins: 534, local_approved_percent: 88, recent_visits: 89,
  },
  {
    slug: 'noodle-and-dumpling-seattle', name: 'Noodle & Dumpling',
    city: 'Seattle', neighborhood: 'International District', cuisine: 'Chinese', price: '$',
    description: 'No-frills noodle shop where hand-pulled noodles are made fresh every 30 minutes. Dumplings: 10 for $8.',
    recommendation_reason: '90% of budget-conscious food lovers say this is the best value in Seattle',
    address: '660 S King St, Seattle, WA 98104', hours: '10am - 8pm daily', phone: null,
    images: ['https://picsum.photos/seed/noodledumpling1/400/300','https://picsum.photos/seed/noodledumpling2/400/300'],
    latitude: 47.5960, longitude: -122.3245,
    tags: ['Cheap Eats','Fresh Noodles','Dumplings','Student Favorite'],
    categories: ['student-favorites','local-approved','hidden-gems'],
    best_for: ['Budget diners','Students','Noodle lovers'],
    avoid_if: ['Want ambiance','Need alcohol'],
    is_open: true, wait_time: null,
    insider_tip: 'The dumplings are best pan-fried (guotie style) — ask even if menu says steamed only.',
    what_locals_order: ['Hand-pulled noodles in beef broth','Pan-fried dumplings (10pc)','Dan dan noodles','Hot & sour soup'],
    best_time_to_go: 'Weekday lunch 12:30pm — freshest noodle batch',
    trending_signal: 'rising', verified_check_ins: 367, local_approved_percent: 90, recent_visits: 54,
  },
  // ── Boston ────────────────────────────────────────────────────────────────
  {
    slug: 'taiwan-cafe-boston', name: 'Taiwan Cafe',
    city: 'Boston', neighborhood: 'Chinatown', cuisine: 'Taiwanese', price: '$',
    description: 'The scallion pancake with egg is flaky and perfect. The three-cup chicken is sticky, savory and salty.',
    recommendation_reason: '93% of Boston Chinatown regulars say Taiwan Cafe is the most consistent',
    address: '34 Oxford St, Boston, MA 02111', hours: '11am - 1am daily', phone: null,
    images: ['https://picsum.photos/seed/taiwancafe1/400/300','https://picsum.photos/seed/taiwancafe2/400/300'],
    latitude: 42.3513, longitude: -71.0626,
    tags: ['Late Night','Taiwanese','Comfort Food','Always Open'],
    categories: ['local-approved','student-favorites','culture-approved'],
    best_for: ['Late-night diners','Comfort food seekers','Students'],
    avoid_if: ['Want a quiet dinner','Need a reservation'],
    is_open: true, wait_time: null,
    insider_tip: 'They serve until 1am — only real late-night Chinese option in Chinatown.',
    what_locals_order: ['Three-cup chicken (三杯雞)','Scallion pancake with egg','Beef noodle soup','Oyster vermicelli'],
    best_time_to_go: 'Any weeknight after 8pm — half the crowd is gone',
    trending_signal: 'classic', verified_check_ins: 489, local_approved_percent: 93, recent_visits: 87,
  },
  {
    slug: 'gourmet-dumpling-house-boston', name: 'Gourmet Dumpling House',
    city: 'Boston', neighborhood: 'Chinatown', cuisine: 'Chinese - Dumplings', price: '$',
    description: 'The soup dumplings (XLB) at GDH are a Boston institution — thin skinned, generously soupy, made 400 times a day.',
    recommendation_reason: '91% of Boston locals say GDH XLB are the best in the city, and it is not close',
    address: '52 Beach St, Boston, MA 02111', hours: '11am - 11pm daily', phone: null,
    images: ['https://picsum.photos/seed/gdh1/400/300','https://picsum.photos/seed/gdh2/400/300'],
    latitude: 42.3508, longitude: -71.0618,
    tags: ['XLB','Boston Institution','Cheap Eats','Always Packed'],
    categories: ['local-approved','student-favorites','culture-approved'],
    best_for: ['Dumpling lovers','Budget diners','Groups'],
    avoid_if: ['Need quiet ambiance','Pork-free'],
    is_open: true, wait_time: '20 min',
    insider_tip: 'Put your name in and walk around the block. Do not wait inside.',
    what_locals_order: ['Pork XLB (2 orders minimum)','Dry fried string beans','Scallion pancake','Wontons in chili oil'],
    best_time_to_go: 'Weekday 11am when they open — hottest XLB of the day',
    trending_signal: 'classic', verified_check_ins: 723, local_approved_percent: 91, recent_visits: 145,
  },
  {
    slug: 'myers-chang-boston', name: 'Myers + Chang',
    city: 'Boston', neighborhood: 'South End', cuisine: 'Chinese - American', price: '$$',
    description: 'Joanne Chang and Christopher Myers created a love letter to Asian-American flavors. The smacked cucumber salad is the best starter in Boston.',
    recommendation_reason: '87% of Boston foodies say Myers + Chang is the most creative Asian restaurant in the city',
    address: '1145 Washington St, Boston, MA 02118', hours: '11:30am - 10pm, closed Mondays', phone: null,
    images: ['https://picsum.photos/seed/myerschang1/400/300','https://picsum.photos/seed/myerschang2/400/300'],
    latitude: 42.3447, longitude: -71.0729,
    tags: ['Asian-American','Creative','Brunch','Date Night'],
    categories: ['date-night','local-approved'],
    best_for: ['Adventurous eaters','Date nights','Brunch'],
    avoid_if: ['Want traditional Chinese','On a strict budget'],
    is_open: true, wait_time: null,
    insider_tip: 'The weekend dim sum brunch is a different menu and worth doing. Book ahead.',
    what_locals_order: ['Smacked cucumber salad','Dan dan noodles','Crispy Chinese sausage fried rice','Steamed bao'],
    best_time_to_go: 'Tuesday dinner — chefs are relaxed, specials are most experimental',
    trending_signal: 'trending', verified_check_ins: 634, local_approved_percent: 87, recent_visits: 112,
  },
  {
    slug: 'fuloon-boston', name: 'Fuloon',
    city: 'Boston', neighborhood: 'Malden', cuisine: 'Chinese - Sichuan', price: '$$',
    description: 'The Sichuan restaurant the Boston Chinese community goes to when they want the real thing. Mapo tofu is electric.',
    recommendation_reason: '95% of Boston Sichuan lovers say Fuloon is authentic and unmissable',
    address: '412 Main St, Malden, MA 02148', hours: '11am - 10pm, closed Tuesdays', phone: null,
    images: ['https://picsum.photos/seed/fuloon1/400/300','https://picsum.photos/seed/fuloon2/400/300'],
    latitude: 42.4272, longitude: -71.0661,
    tags: ['Authentic Sichuan','Spicy','Numbing','Worth the Trip'],
    categories: ['actually-spicy','local-approved','culture-approved','hidden-gems'],
    best_for: ['Sichuan food seekers','Spice lovers','Authentic seekers'],
    avoid_if: ['Low heat tolerance','Want convenience'],
    is_open: true, wait_time: null,
    insider_tip: 'Order the water-boiled fish (shui zhu yu) and ask for it extra spicy.',
    what_locals_order: ['Mapo tofu (extra spicy)','Water-boiled beef','Twice-cooked pork','Dan dan noodles','Cold sesame noodles'],
    best_time_to_go: 'Sunday dinner — families bring big tables, energy is great',
    trending_signal: 'underrated', verified_check_ins: 398, local_approved_percent: 95, recent_visits: 61,
  },
  {
    slug: 'peach-farm-boston', name: 'Peach Farm',
    city: 'Boston', neighborhood: 'Chinatown', cuisine: 'Chinese - Cantonese Seafood', price: '$$',
    description: 'The most famous late-night seafood spot in Boston Chinatown. Salt and pepper shrimp served shell-on.',
    recommendation_reason: '90% of Boston night owls and Chinatown regulars swear by Peach Farm',
    address: '4 Tyler St, Boston, MA 02111', hours: '11am - 2am daily', phone: null,
    images: ['https://picsum.photos/seed/peachfarm1/400/300','https://picsum.photos/seed/peachfarm2/400/300'],
    latitude: 42.3516, longitude: -71.0635,
    tags: ['Late Night','Seafood','Chinatown Staple','Always Open'],
    categories: ['local-approved','culture-approved','student-favorites'],
    best_for: ['Late-night dining','Seafood lovers','Large groups'],
    avoid_if: ['Shellfish allergic','Looking for ambiance'],
    is_open: true, wait_time: null,
    insider_tip: 'Order from the specials board — it changes daily based on the fish market.',
    what_locals_order: ['Salt & pepper shrimp (whole)','Steamed fish with ginger','Clams in black bean sauce','Hong Kong style beef chow fun'],
    best_time_to_go: 'Friday 11pm — kitchen is energetic, staff in great mood',
    trending_signal: 'classic', verified_check_ins: 556, local_approved_percent: 90, recent_visits: 101,
  },
];

// ── Insert one-by-one ──────────────────────────────────────────────────────
async function insertOne(restaurant, index) {
  const url = `${SUPABASE_URL}/rest/v1/restaurants`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Prefer': 'resolution=merge-duplicates',
      'apikey': SERVICE_ROLE_KEY,
      'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
    },
    body: JSON.stringify(restaurant),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`HTTP ${res.status} on "${restaurant.name}": ${text.slice(0, 200)}`);
  }
  process.stdout.write(`  [${String(index + 1).padStart(2, '0')}/${restaurants.length}] ✓ ${restaurant.name}\n`);
}

async function seed() {
  console.log(`\nSeeding ${restaurants.length} restaurants to ${SUPABASE_URL}...\n`);
  let failed = 0;
  for (let i = 0; i < restaurants.length; i++) {
    try {
      await insertOne(restaurants[i], i);
    } catch (e) {
      console.error(`  ❌  ${e.message}`);
      failed++;
    }
  }
  console.log(`\n${failed === 0 ? '✅' : '⚠️ '} Done. ${restaurants.length - failed} seeded, ${failed} failed.\n`);
}

seed().catch((err) => { console.error('❌  Seed crashed:', err.message); process.exit(1); });
